name: "SMZDM Check-in Bot"

on:
  workflow_dispatch:

  # 取消下面两行注释，务必自行更改为随机时间
  # schedule:
  #   - cron: "30 1 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          SMZDM_COOKIE: __ckguid=9UV67ObH3lug71327ixBavH6; device_id=21307064331675733756223526507b5d4c3efba2cc291aa60135992674; homepage_sug=c; r_sort_type=score; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1675733754; user=para|7223356365; smzdm_id=7223356365; footer_floating_layer=0; ad_date=15; ad_json_feed={}; sensorsdata2015jssdkcross={"distinct_id":"1862983dede517-03dc45a2b17ed6-26021051-2073600-1862983dedf10a8","first_id":"","props":{"$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":""},"$device_id":"1862983dede517-03dc45a2b17ed6-26021051-2073600-1862983dedf10a8"}; sess=BA-0qyVPZ+Uk83fm1JCNeMFRHCXFSmsGSIopvUpTWhkJIcASUvYjJ5uSjhMDL49xKAp27xjpuL+W7hKF9pJZLxnuFKGRFk8jOWOWkqxXke1C2Wv3nWm8qDBIJsH; _zdmA.vid=*; _zdmA.uid=ZDMA.8gLcUrdIb.1676450003.2419200; bannerCounter=[{"number":1,"surplus":1},{"number":0,"surplus":5},{"number":0,"surplus":1},{"number":0,"surplus":1},{"number":0,"surplus":1},{"number":0,"surplus":1}]; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1676450006; _zdmA.time=1676450033708.0.https://www.smzdm.com/
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SC_KEY: ${{ secrets.SC_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python main.py
